version: '3.3'
services:
 avreg:
    container_name: avreg-server
    image: avreg-server:latest
    restart: always
    volumes:
      - /data/avreg:/var/spool/avreg
      - /data/avreg-db:/var/lib/mysql:rw
    network_mode: host
